### ISSUE TITLE
May I ask if your Python LSP's inlay hint feature is working?

### ISSUE THREAD

**Issue by Fau818** [tiagovla/.dotfiles#3]
I found the `inlay hint` only works on single file mode on my neovim.

**Comment by tiagovla** [comment]
I just tested it in single file mode, and with a root, both are working.

**Comment by Fau818** [comment]
Thanks for your reply.
Unfortunately, I just tested your neovim config, but I cannot reproduce the inlay hints.

Just to be sure, you can still see type hints when using the `LspInfo` command to check the status of pylance, and if pylance is NOT in "root directory: Running in single file mode".

To avoid ambiguity, I've posted the demo image below which only works with a single file for me.

<img width="767" alt="image" src="https://github.com/tiagovla/.dotfiles/assets/75115028/d8fd6758-614d-40ba-bfa3-6017241f103e">

EDIT: Sorry, I just tested your neovim configuration and reproduced the inlay hints successfully. Please ignore the question above, thanks again!

**Comment by Fau818** [comment]
I found the problem, and it is necessary to set the value of `settings.python.pythonPath`.

Thanks for the inspiration of your dotfiles.
