### ISSUE TITLE
Typo in treesitter config

### ISSUE THREAD

**Issue by DannyStoll1** [tiagovla/.dotfiles#4]
There appears to be a typo in the treesitter config:

```
-- neovim/.config/nvim/lua/plugins/modules/treesitter.lua
-- [...]
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = "gnn",
                node_umental = "gnn",
                scope_incremental = "gns",
                node_decremental = "gnp",
            },
        },
```

The above gives rise to an [error](https://github.com/nvim-treesitter/nvim-treesitter/issues/6025) with the latest version of treesitter, since `node_umental` is not a valid function descriptor. Too lazy to make a PR, but you probably want to replace the above with

```
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = "gnn",
                node_incremental = "gnn",
                scope_incremental = "gns",
                node_decremental = "gnp",
            },
        },
```

Presumably, the keymap should also be different from `init_selection`, but that's of course up to you.

**Comment by tiagovla** [comment]
Thanks!
